### ISSUE TITLE
Cryptic runtime error

### ISSUE THREAD

**Issue by CrackedP0t** [thecodingcouple/phaser-es2015#1]
If I add the code `this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;` under the `super(` statement in `game.js`, I get a cryptic error from SystemJS in Firefox. Is there a way to actually show the problem with the code?

Note: In Chrome, I get an actual descriptive error.

**Comment by nsipid** [comment]
You need to wait until the game is in the first state before `this.scale` will be non-null.  We can move the constructor logic to a default initial state to fix this problem:

```
// src/game.js

import Phaser from 'phaser';
import { Load } from './states/load';
import { Menu } from './states/menu';
import { Play } from './states/play';
import { GameOver } from './states/gameover';
import { Victory } from './states/victory';

export class Game extends Phaser.Game {
    constructor() {
        super(800, 600, Phaser.AUTO, 'phaser-canvas', { create: () => {
            this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;

            this.state.add('load', Load);
            this.state.add('menu', Menu);
            this.state.add('play', Play);
            this.state.add('gameover', GameOver);
            this.state.add('victory', Victory);

            this.state.start('load');
        }});
    }
}
```

Thanks for pointing this out!  The skeleton will be updated to prevent further confusion.
